import React from 'react';
import '../Credits'
import '../SampleEmail'
import { Layout, Menu, Button, Typography } from 'antd';
import Credits from '../Credits';
import SampleEmail from '../SampleEmail';
import * as QueryString from "query-string";

const { Header, Footer, Sider, Content } = Layout;
const { Title } = Typography

// Example POST method implementation:
async function postData(url = '', data = {}) {
  // Default options are marked with *
  const response = await fetch(url, {
    method: 'POST', // *GET, POST, PUT, DELETE, etc.
    headers: {
      'Content-Type': 'application/json'
      // 'Content-Type': 'application/x-www-form-urlencoded',
    },
    body: JSON.stringify(data) // body data type must match "Content-Type" header
  });
  return response.json(); // parses JSON response into native JavaScript objects
}

function App(props) {
  //EXAMPLE REQUEST
  // postData('/send_emails', { code: 'suuuuuuuuuuuup', subject: 'subject', states:['California'], scopes: scopes })
  // .then(data => {
  //   console.log(data); // JSON data parsed by `response.json()` call
  // });
  const params = QueryString.parse(props.location.search);
  console.log(params);
  const code = params.code;
  const scopes = params.scope;
  return (
    <Layout className="layout" style={{ opacity:'0.8'}}>
      <meta></meta>
     <Header>
       <div className="logo" />
       <Menu theme="dark" mode="horizontal" defaultSelectedKeys={['1']}>
         <Menu.Item key="1"><a href='#home'>Home</a></Menu.Item>
         <Menu.Item key="2"> <a href='#about'></a>About</Menu.Item>
         <Menu.Item key="3"> <a href='https://how-can-i-help.github.io/' target="_blank"> Resources </a> </Menu.Item>
         <Menu.Item key="4">Submit a representative</Menu.Item>
       </Menu>
     </Header>
    <Layout>
      <Content id='home' style={{ padding: '25px 50px', backgroundColor: '#003261'}}>
            <Title style={{ color: 'pink'}}>Reach out to your representatives quickly and efficiently.</Title>
            <Title level={2} style={{ color: 'white'}}>In light of recent events, We have created this tool to send emails 
              (using the template from nomoreracistcops.github.io) to a list of <b>188</b> elected US officials.
              These emails will be generated by <b><a href="https://github.com/alandgton/activism-mailbot">mail-bot</a></b>, which will be automatically sent to the representatives selected through your app.
              </Title>
              <Title level={3} style={{ textAlign: 'left', color: 'white'}}>How to use this page:</Title>
            <ol>
              <li>Click the 'Get Started' button.</li>
              <li>This will ask you to sign in with a Google account of your choice.</li>
              <li>You will then be redirected to a page where you can <u>select which representatives</u> you wish to send your emails to.
                You can select all or select by state for now.</li>
              <li>Hit send and your emails should start being sent automatically! </li>
              <li>Additionally, if you don't see your local representative listed, Find the <u>email addresses</u> of your <u>local police</u> department, local representatives, <u>county</u> representatives, <u>and state</u> representatives and submit them through <a href="https://forms.gle/Duy52iF4i5kvyb9K8">this form.</a></li>
              <li>Share with others</li>
              <li>Keep reporting abusive officers and <u>demanding they be fired and charged, not just 'investigated'</u></li>
            </ol>
            <Button style={{ marginTop: '20px' }}type='primary' size='large' block> Let's get started </Button>
      </Content>
      <Sider width='700' style={{ textAlign: 'center', padding: '25px 50px' }}>
        <SampleEmail></SampleEmail>
      </Sider>
    </Layout>

     <Footer style={{ textAlign: 'center' }}>
      <Title level={3} id='about' style={{ padding: '25px 0px 25px'}}> Big thanks to those who are helping make this possible.</Title>
       <Credits></Credits>
     </Footer>
   </Layout>
  );
}

export default App;
